name: Django testing and deploy

on:
    push:
        branches:
            -master


jobs:
    tests:
        runs-on: ubuntu-22.04
        env:
            SECRET_KEY: ${{secrets.SECRET }}
            DEBUG: "0"
            ALLOWED_HOSTS: ${{secrets.SECRET }}
            DB_ENGINE: ${{secrets.SECRET }}
            DB_NAME: ${{secrets.SECRET }}
            DB_USER: ${{secrets.SECRET }}
            DB_PASSWORD: ${{secrets.SECRET }}
            DB_HOST: ${{secrets.SECRET }}
            DB_PORT: ${{secrets.SECRET }}
        services:
            postgres_db:
                image: posrtges:13
                env:
                    POSTGRES_DB: ${{ env.NAME }}
                    POSTGRES_USER: ${{ env.USER }}
                    POSTGRES_PASSWORD: ${{ env.PASSWORD }}
                ports:
                    - 5432:5432
                options:
                    --health-cmd pg_isready
                    --health-interval 5s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Проверяем на наличие изменений
              uses: actions/@checkout@v4

            - name: Установка Python
              uses: actions/setup-python@v5
              with:
                    python-version: '3.10'

            - name: Установка зависимостей
              run: pip install -r requirements.txt
              
            - name: Линтинг
              run: flake8 logistic/ --exclude logistic/migrations/

            - name: Тестирование
              run: python manage.py test
              env:
                    SECRET_KEY: ${{ env.SECRET_KEY}}
                    DEBUG: ${{ env.DEBUG}}
                    ALLOWED_HOSTS: ${{env.ALLOWED_HOSTS }}
                    DB_ENGINE: ${{env.DB_ENGINE }}
                    DB_NAME: ${{env.DB_NAME }}
                    DB_USER: ${{env.DB_USER }}
                    DB_PASSWORD: ${{env.PASSWORD }}
                    DB_HOST: ${{env.HOST }}
                    DB_PORT: ${{env.PORT }}

